from Bio import Align
from Bio.Seq import Seq
import Bio.SeqIO as SeqIO
from Bio.Alphabet import generic_dna, generic_protein
from Bio import pairwise2
# Import format_alignment method
from Bio.pairwise2 import format_alignment


def align_sequences(seq1, seq2, local=False):
    if local:
        aligner.mode = "local"
    score = aligner.score(seq1, seq2)
    return score

aligner = Align.PairwiseAligner()
seqK3VAW3 = 'MIFTAPAYAPALPSPLPLQQTIGDFCLAKRRERQGASDSLFIEAAIDRKWTIDDIEARLGRMAAALSSAW \
NITPGQKWHKTVAILASNCVDTLILSWAVHRIGGGCLMLQPTSSADEMAAHMDRVPPFAMFLSQDLLTLG \
QEAFQKSSLSSNVPFYSFSGAEAPKPQQTAVPVASQDAPNISTLDDLMATGKELPLLEKTSFSEGEASRR \
VAYYCTTSGTSGFQRVVAITHENIIASILQAGLFIEATKGPASEVTLAFLPFNHIYGLLITHTFTWRGDS \
TVVHSGFNMMEILISIGKHRINTLYLVPPIINALSRNASILDRFDMSSVRYIVNGGGPLPKEAFLKMKAA \
RPDWQIIPGWGQTEGCGIGSLSSPKDIFPGSSGVLLPGVRIRLRDDDGRIVQGLEEMGEIEIESPSGLFG \
YVDYADEALLSPPKEEEFWWPTGDVGLFRISPNGEQHLFIVDRIRDMIKVKGNQVAPGQIEDHLTKHAAV \
AETAVIGIADEVAGERALAFIVRESSHAREMSEADLRKIIQEHNDLELPEVCRLQDRIIFVDELPKSASG \
KILKRELRKQVATWSPPQK'

seqQ6GZX4 = 'CWVSKFKDAMRRYQGIQTCKIPGKVLSDLDAKIKAYNLTVEGVEGFVRYS \
RVTKQHVAAFLKELRHSKQYENVNLIHYILTDKRVDIQHLEKDLVKDFKALVESAHRMRQGHMINVKYIL \
YQLLKKHGHGPDGPDILTVKTGSKGVLYDDSFRKIYTDLGWKFTPL'


print(align_sequences(seqK3VAW3, seqQ6GZX4 ))

alignments = pairwise2.align.localxx(seqK3VAW3, seqQ6GZX4 )
print('2')
print('')
print(alignments[0][2])